export const ACHIEVEMENTS = {
  WORKOUT_MILESTONES: {
    BEGINNER: {
      count: 5,
      points: 500,
      id: "workout-beginner",
      badge: "beginner-athlete",
      name: "Workout Beginner",
      img: "/badges/beginner.svg",
    },
    INTERMEDIATE: {
      count: 25,
      points: 1000,
      id: "workout-intermediate",
      badge: "dedicated-athlete",
      name: "Workout Intermediate",
      img: "/badges/intermediate.svg",
    },
    ADVANCED: {
      count: 100,
      points: 2500,
      id: "workout-advanced",
      badge: "advanced-athlete",
      name: "Workout Advanced",
      img: "/badges/advanced.svg",
    },
    ELITE: {
      count: 500,
      points: 5000,
      id: "workout-elite",
      badge: "elite-athlete",
      name: "Workout Elite",
      img: "/badges/elite.svg",
    },
  },
  STREAK_MILESTONES: {
    CONSISTENT: {
      days: 7,
      points: 700,
      id: "streak-week",
      badge: "weekly-warrior",
      name: "Streak Week",
      img: "/badges/streak-week.svg",
    },
    DEDICATED: {
      days: 30,
      points: 3000,
      id: "streak-month",
      badge: "monthly-master",
      name: "Streak Month",
      img: "/badges/streak-month.svg",
    },
    UNSTOPPABLE: {
      days: 100,
      points: 10000,
      id: "streak-century",
      badge: "unstoppable-force",
      name: "Streak Century",
      img: "/badges/streak-century.svg",
    },
  },
  LEVEL_MILESTONES: {
    NOVICE: {
      level: 5,
      points: 1000,
      id: "level-novice",
      badge: "rising-star",
      name: "Level Novice",
      img: "/badges/level-novice.svg",
    },
    INTERMEDIATE: {
      level: 10,
      points: 2000,
      id: "level-intermediate",
      badge: "power-player",
      name: "Level Intermediate",
      img: "/badges/level-intermediate.svg",
    },
    EXPERT: {
      level: 25,
      points: 5000,
      id: "level-expert",
      badge: "grandmaster",
      name: "Level Expert",
      img: "/badges/level-expert.svg",
    },
  },
} as const;
